# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "font-awesome-4.7.0" = {
      name = "font-awesome";
      packageName = "font-awesome";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz";
        sha1 = "8fa8cf0411a1a31afd07b06d2902bb9fc815a133";
      };
    };
    "js-yaml-3.12.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.12.0.tgz";
        sha512 = "PIt2cnwmPfL4hKNwqeiuz4bKfnzHTBv6HyVgjahA6mPLwPDzjDWrplJBMjHUFxku/N3FlmrbyPclad+I+4mJ3A==";
      };
    };
    "material-design-icons-3.0.1" = {
      name = "material-design-icons";
      packageName = "material-design-icons";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-design-icons/-/material-design-icons-3.0.1.tgz";
        sha1 = "9a71c48747218ebca51e51a66da682038cdcb7bf";
      };
    };
    "material-icons-0.2.3" = {
      name = "material-icons";
      packageName = "material-icons";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-icons/-/material-icons-0.2.3.tgz";
        sha512 = "1Q5wp4aeGWjE5POMtdLmqJn94QM7vmUCeJhNO5m0oDrtW1jfWlaLK73vF3C7/fuMD7NIVicyK8TSkwd+diFgaQ==";
      };
    };
    "npm-font-open-sans-1.1.0" = {
      name = "npm-font-open-sans";
      packageName = "npm-font-open-sans";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-font-open-sans/-/npm-font-open-sans-1.1.0.tgz";
        sha512 = "t1y5ShWm6a8FSLwBdINT47XYMcuKY2rkTBsTdz/76YB2MtX0YD89RUkY2eSS2/XOmlZfBe1HFBAwD+b9+/UfmQ==";
      };
    };
    "npm-font-open-sans-condensed-1.0.3" = {
      name = "npm-font-open-sans-condensed";
      packageName = "npm-font-open-sans-condensed";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-font-open-sans-condensed/-/npm-font-open-sans-condensed-1.0.3.tgz";
        sha1 = "92cc26616f93a2d76e8807243058aac4d4d22216";
      };
    };
    "raleway-webfont-3.0.1" = {
      name = "raleway-webfont";
      packageName = "raleway-webfont";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/raleway-webfont/-/raleway-webfont-3.0.1.tgz";
        sha1 = "12bf6b081558fde0717df5a97cc17f076d1eabfa";
      };
    };
    "roboto-fontface-0.10.0" = {
      name = "roboto-fontface";
      packageName = "roboto-fontface";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.10.0.tgz";
        sha512 = "OlwfYEgA2RdboZohpldlvJ1xngOins5d7ejqnIBWr9KaMxsnBqotpptRXTyfNRLnFpqzX6sTDt+X+a+6udnU8g==";
      };
    };
    "source-sans-pro-2.20.2" = {
      name = "source-sans-pro";
      packageName = "source-sans-pro";
      version = "2.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-sans-pro/-/source-sans-pro-2.20.2.tgz";
        sha512 = "/HW4xC0C9KjeyE/lmZxZKYaQgdde1QTBQG3ynNpvWJKb1l93dsiBF31OlGmxJAZH2oeLeWAn9v7g7z2aDkrEUw==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "vue-2.5.17" = {
      name = "vue";
      packageName = "vue";
      version = "2.5.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue/-/vue-2.5.17.tgz";
        sha512 = "mFbcWoDIJi0w0Za4emyLiW72Jae0yjANHbCVquMKijcavBGypqlF7zHRgMa5k4sesdv7hv2rB4JPdZfR+TPfhQ==";
      };
    };
    "vue-router-3.0.1" = {
      name = "vue-router";
      packageName = "vue-router";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-router/-/vue-router-3.0.1.tgz";
        sha512 = "vLLoY452L+JBpALMP5UHum9+7nzR9PeIBCghU9ZtJ1eWm6ieUI8Zb/DI3MYxH32bxkjzYV1LRjNv4qr8d+uX/w==";
      };
    };
  };
  args = {
    name = "best-resume-ever";
    packageName = "best-resume-ever";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."argparse-1.0.10"
      sources."esprima-4.0.1"
      sources."font-awesome-4.7.0"
      sources."js-yaml-3.12.0"
      sources."material-design-icons-3.0.1"
      sources."material-icons-0.2.3"
      sources."npm-font-open-sans-1.1.0"
      sources."npm-font-open-sans-condensed-1.0.3"
      sources."raleway-webfont-3.0.1"
      sources."roboto-fontface-0.10.0"
      sources."source-sans-pro-2.20.2"
      sources."sprintf-js-1.0.3"
      sources."vue-2.5.17"
      sources."vue-router-3.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Build fast and easy multiple beautiful resumes and create your best CV ever! ";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}